steps:
  ############################################################
  # Run TPT script
  ############################################################
- name: teradata/tpt:latest
  entrypoint: bash
  args:
    - run_tpt.sh
  env:
    - accept_license=Y
    - "SELECT_STATEMENT=SELECT * FROM tpch.orders;"
  secretEnv: 
    - GCS_ACCESS_KEY_ID
    - GCS_SECRET_ACCESS_KEY
    - TERADATA_PASSWORD
options:
  pool:
    name: projects/${PROJECT_ID}/locations/us-central1/workerPools/tpt 

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/gcs_access_key_id/versions/latest
    env: 'GCS_ACCESS_KEY_ID'
  - versionName: projects/$PROJECT_ID/secrets/gcs_secret_access_key/versions/latest
    env: 'GCS_SECRET_ACCESS_KEY'
  - versionName: projects/$PROJECT_ID/secrets/teradata_password/versions/latest
    env: 'TERADATA_PASSWORD'