steps:
  # Install the Python dependencies you need for your DAGs
  # Pin dependencies to the same versions used in your Composer instance by specifying a constraints file
  # https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#constraints-files
  # Match your Airflow & Python version using the following templated link:
  # https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt
  - name: python:3.11.8-slim
    script: |
      #!/usr/bin/env bash
      python3 -m venv venv
      pip install \
        --requirement composer/tests/requirements.txt \
        --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.10.2/constraints-3.11.txt \
        --user
  # Run DAG unit tests 
  - name: apache/airflow:2.10.2-python3.11
    dir: composer
    script: |
      #!/usr/bin/env bash
      airflow standalone
      source venv/bin/activate
      python3 -m pytest -s tests
  # Copy DAGs to the Composer /dags Cloud Storage folder only if unit tests pass
  - name: gcr.io/cloud-builders/gcloud
    script: |
      #!/usr/bin/env bash
      gcloud storage cp composer/dags/*.py gs://us-central1-small-3cd6c755-bucket/dags/