steps:
  # install dependencies
  - name: python:3.11.8-slim
    entrypoint: pip
    args: [
      "install", 
      "--requirement",
      "composer/tests/requirements.txt",
      "--constraint",
      # Pin dependencies to the same versions used in your Composer instance by specifying a constraints file
      # https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#constraints-files
      # Match your Airflow & Python version using the following templated link:
      # https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt
      "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.2/constraints-3.11.txt",
      "--user"
    ]

  # run in python 3.11 which is latest version in Cloud Composer
  - name: python:3.11.8-slim
    entrypoint: python3.11
    args: ["-m", "pytest", "-s", "composer/tests/"]