steps:
  ############################################################
  # Run TPT script
  ############################################################
- name: teradata/tpt:latest
  script: |
    #!/bin/bash
    set -eo pipefail  # Enable exit-on-error mode
    tbuild -f export.tpt -u "
      TD_HOSTNAME='${TERADATA_HOSTNAME}',
      TD_USERNAME='dbc',
      TD_PASSWORD='${TERADATA_PASSWORD}',
      SELECT_STMT='${SELECT_STATEMENT}',
      jobvar_accessmoduleinitstr='
        Bucket=${GCS_BUCKET}
        Prefix=${GCS_PREFIX}
        Object=data.csv
        MaxObjectSize=100M 
        ConnectionCount=20
      '
    "
  env:
    - accept_license=Y
    - TERADATA_HOSTNAME=${_TERADATA_HOSTNAME}
    - SELECT_STATEMENT=${_SELECT_STATEMENT}
    - GCS_BUCKET=${_GCS_BUCKET}
    - GCS_PREFIX=${_GCS_PREFIX}

  secretEnv: 
    - GCS_ACCESS_KEY_ID
    - GCS_SECRET_ACCESS_KEY
    - TERADATA_PASSWORD

substitutions:
  _TERADATA_HOSTNAME: "10.128.0.26"
  _SELECT_STATEMENT: "SELECT * FROM tpch.orders;"
  _GCS_BUCKET: "dannybq"
  _GCS_PREFIX: "orders/"

options:
  pool:
    name: projects/${PROJECT_ID}/locations/us-central1/workerPools/tpt 

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/gcs_access_key_id/versions/latest
    env: 'GCS_ACCESS_KEY_ID'
  - versionName: projects/$PROJECT_ID/secrets/gcs_secret_access_key/versions/latest
    env: 'GCS_SECRET_ACCESS_KEY'
  - versionName: projects/$PROJECT_ID/secrets/teradata_password/versions/latest
    env: 'TERADATA_PASSWORD'